### ISSUE TITLE
Hyphen

### ISSUE THREAD

**Issue by plushxwx** [Nerixyz/current-song2#530]
Hyphen in song title causes wrong artist to display, this only happens with some songs:
https://soundcloud.com/st-ars-tar-star-sta-r/sophie-just-like-we-never-said-goodbye-revamp appears like this
![add9dbca1d9650e2d5632de9cc67e065](https://github.com/user-attachments/assets/ba4568bd-2d55-4501-8eef-1bbe47e81e8d)

https://soundcloud.com/jumang4423/computer-city-mediumcore-edit appears like this
![857e4871782eb8a2cc320f0ec3876fc9](https://github.com/user-attachments/assets/9ec9a510-6fff-4a3c-bc3f-4862c1e26363)

https://soundcloud.com/leondismusic/tasteleondisremix appears like this
![482bf4333b59efaded5e5eddb7fb878d](https://github.com/user-attachments/assets/40c08835-1d0d-438f-a74d-d71f2e559ed2)

https://soundcloud.com/st-ars-tar-star-sta-r/mental-im-mad-me-mix appears like this
![0aaa64f467cf3562f113ae755468b728](https://github.com/user-attachments/assets/f84f9652-7391-46ee-9483-1f975fc748f6)

https://soundcloud.com/iamwolfmagic/dog-blood-break-law-wolfmagic-edit appears like this
![e3914ad7c3e0895837e0b9d5fc24a3f2](https://github.com/user-attachments/assets/24aaafd8-73ef-4739-bcb3-ba2e02cce1cd)

**Comment by Nerixyz** [comment]
There are [a few utilities that try to "clean up" the information from "server"](https://github.com/Nerixyz/current-song2/blob/25c03c8d4638c9a420aae96d9afae87aef140681/js/client/src/text/index.ts#L10-L59), because often, the artist isn't the desired artist or duplicate (on YouTube for example, the artist is always the channel name). I'm not sure what the ideal path would be here, because we don't really know where a song comes from. Maybe there could be a setting to disable any cleanup?

**Comment by Nerixyz** [comment]
You can now add `use-raw-data` to the query (e.g. `http://localhost:48457/?use-raw-data`) and it will skip the cleanup.

Should be in the [nightly build](https://github.com/Nerixyz/current-song2/releases/tag/nightly-build) in a few minutes.
